const:
  foo: bar
packages:
- name: helloworld
  type: generic
  ephemeral: true
  config:
    commands:
    - ["echo", "hello world"]
- name: app
  type: go
  srcs:
  - "**/*.go"
  - go.mod
  - go.sum
  deps:
  - :helloworld
  argdeps:
  - version
  prep:
  - ["echo", "hello prep"]
  config:
    buildArgs:
    - -ldflags
    - -X main.version=${version}
    library: false
scripts:
- name: env
  description: prints the environment variables of the script execution context
  deps:
  - :app
  script: |
    env
- name: pwd
  description: prints the current working directory of the script
  workingdirLayout: packages
  deps:
  - :app
  script: |
    pwd